# Generated by Django 6.0.7 on 2026-07-27 12:51

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0001_initial'),
        ('recipes', '0002_favoriterecipe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pantryitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01, message='Quantity must be greater than zero.')]),
        ),
        migrations.AddConstraint(
            model_name='pantryitem',
            constraint=models.UniqueConstraint(fields=('user', 'ingredient'), name='unique_user_pantry_ingredient'),
        ),
    ]
