# Generated by Django 6.0.7 on 2026-07-29 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0002_alter_pantryitem_unique_together_and_more'),
        ('recipes', '0003_recipe_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pantryitem',
            options={'ordering': ['expiration_date']},
        ),
        migrations.RemoveConstraint(
            model_name='pantryitem',
            name='unique_user_pantry_ingredient',
        ),
        migrations.AddConstraint(
            model_name='pantryitem',
            constraint=models.UniqueConstraint(fields=('user', 'ingredient', 'expiration_date'), name='unique_user_ingredient_expiration'),
        ),
    ]
